### ISSUE TITLE
[KaptException] Can't get project to build

### ISSUE THREAD

**Issue by ziSo12** [VMadalin/android-modular-architecture#25]
## Description
I can't get the project to build. Please see below stack trace.
Any idea on how to solve this issue?
Thanks null

## Basic Information

-   Device type: -
-   OS version: -
-   App version: 1.0

## Details

```text
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':commons:ui:kaptDevDebugKotlin'

........

Caused by: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.doLoadProcessors(ProcessorLoader.kt:80)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:45)
Caused by: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor

	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:42)
	... 29 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	... 35 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	... 35 more
```

**Comment by ziSo12** [comment]
Problem fixed by changing project SDK from Java 11 to Java 8 according to [this stackoverflow answer](https://stackoverflow.com/a/53517268/11278807)
