### ISSUE TITLE
[ClassNotFoundException] Release build crashing

### ISSUE THREAD

**Issue by ziSo12** [VMadalin/android-modular-architecture#27]
## Description

After running **assembleRelease** gradle task and installing **app-prod-release.apk**/**app-dev-release.apk** the app is crashing with below exception.
I suspect the proguard-rules.pro should contain a keep rule for "coil.util.CoilContentProvider" 

[Edit]
add
-keep class coil.util.CoilContentProvider
to proguard-rules.pro file in ":commons:ui"

add
 consumerProguardFiles("proguard-rules.pro")
to defaultConfig in buildSrc package commons

does not resolve the issue. 

## Basic Information

-   Device type: Pixel 3a emulator
-   OS version: Android 10 (Api 29)
-   App version: 1.0

## Details

```text
2020-10-05 15:03:00.786 13091-13091/com.vmadalin.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vmadalin.android.dev, PID: 13091
    java.lang.RuntimeException: Unable to get provider coil.util.CoilContentProvider: java.lang.ClassNotFoundException: Didn't find class "coil.util.CoilContentProvider" on path: DexPathList[[zip file "/data/app/~~jPJiP2XBCKXTWxQ3bLufAA==/com.vmadalin.android.dev-1EJOzTC0mWHGgspZplp8Yg==/base.apk"],nativeLibraryDirectories=[/data/app/~~jPJiP2XBCKXTWxQ3bLufAA==/com.vmadalin.android.dev-1EJOzTC0mWHGgspZplp8Yg==/lib/x86, /system/lib, /system_ext/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "coil.util.CoilContentProvider" on path: DexPathList[[zip file "/data/app/~~jPJiP2XBCKXTWxQ3bLufAA==/com.vmadalin.android.dev-1EJOzTC0mWHGgspZplp8Yg==/base.apk"],nativeLibraryDirectories=[/data/app/~~jPJiP2XBCKXTWxQ3bLufAA==/com.vmadalin.android.dev-1EJOzTC0mWHGgspZplp8Yg==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(Unknown Source:0)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7228)
```

**Comment by ziSo12** [comment]
My bad. The issue was that I tried to build a signed apk instead of a signed app bundle, which obviously doesn't work with dynamic features.
