### ISSUE TITLE
I don't understand how id(BuildPlugins.NAVIGATION_SAFE_ARGS) works

### ISSUE THREAD

**Issue by alexandru-calinoiu** [VMadalin/android-modular-architecture#30]
## Description

Trying to use this as the base for a new project, but I can't get past this line in `app/build.gradle.kts`

```
    id(BuildPlugins.NAVIGATION_SAFE_ARGS)
```

I get the following error when syncing gradle files

```
org.gradle.internal.exceptions.LocationAwareException: Build file '/home/calin/Projects/reasig/android/app/build.gradle.kts' line: 1
Plugin [id: 'androidx.navigation.safeargs.kotlin'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:214)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$4(DefaultPluginRequestApplicator.java:146)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:207)
	at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:201)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:144)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:84)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:198)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:360)
```

**Comment by alexandru-calinoiu** [comment]
Got it, needs to be included in buildSrc/build.gradle.kts
